/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'category',
      label: '产品',
      items: ['vision', 'roadmap', 'design-principles'],
    },
    {
      type: 'category',
      label: '工程',
      items: [
        'architecture',
        'development',
        'deployment',
        'security-model',
        'performance-budget',
        'regression-checklist',
      ],
    },
    {
      type: 'category',
      label: 'ADR',
      items: [
        { type: 'autogenerated', dirName: 'adr' },
      ],
    },
  ],
};

module.exports = sidebars;
