/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'category',
      label: '使用指南',
      collapsed: false,
      items: [
        'guide/intro',
        'guide/what-is-erd-online',
        'guide/save-version-and-diff',
        'guide/import-dbml',
        'guide/reverse-engineer',
        'guide/roles-and-approval',
        {
          type: 'link',
          label: '与其它工具对照',
          href: 'https://www.erdonline.com/compare',
        },
      ],
    },
    {
      type: 'category',
      label: '自托管与开放接口',
      collapsed: false,
      items: [
        'guide/quick-self-host',
        'deployment',
        'data-format',
        'guide/api-and-mcp',
        'security-model',
      ],
    },
    {
      type: 'category',
      label: '贡献与工程',
      collapsed: true,
      items: [
        'community',
        'development',
        'architecture',
        'vision',
        'roadmap',
        'design-principles',
        'performance-budget',
        {
          type: 'category',
          label: 'ADR',
          items: [{ type: 'autogenerated', dirName: 'adr' }],
        },
        'guide/docs-qa-checklist',
      ],
    },
  ],
};

module.exports = sidebars;
